ADFILES = $(shell find . -type f -name '*.adjs')
MACROS = src/ad/macros.js
TRANSFORM = src/ad/transform
TRANSFORMLIB = src/ad/transform.js
ADFILES_TRANSFORMED = $(ADFILES:.adjs=.js)


all: $(ADFILES_TRANSFORMED)

src/%.js: src/%.adjs $(MACROS) $(TRANSFORM) $(TRANSFORMLIB)
	$(TRANSFORM) $< > $@

clean:
	rm -f $(ADFILES_TRANSFORMED)